import { execSync } from "child_process";
import chalk from "chalk";
import { HealResult, FilePatch } from "../healer/healer.js";
import { ScoredPatch } from "../healer/confidence.js";
import { ApiChange } from "../differ/types.js";

export interface PrOptions {
  baseBranch?: string;
  draft?: boolean;
  perFile?: boolean;
  labels?: string[];
  reviewers?: string[];
  assignees?: string[];
}

export interface PrResult {
  url: string;
  number: number;
  branch: string;
  title: string;
}

/**
 * Creates PRs for heal results. Can create either:
 * - One PR per API change (groups all file patches together)
 * - One PR per affected file (for granular review)
 */
export async function createHealPrs(
  result: HealResult,
  scoredPatches: ScoredPatch[],
  options: PrOptions = {},
): Promise<PrResult[]> {
  ensureGitClean();
  ensureGhCli();

  const baseBranch = options.baseBranch ?? getCurrentBranch();
  const results: PrResult[] = [];

  if (options.perFile) {
    for (const patch of scoredPatches) {
      const pr = await createSingleFilePr(
        result,
        patch,
        baseBranch,
        options,
      );
      if (pr) results.push(pr);
    }
  } else {
    const pr = await createGroupedPr(result, scoredPatches, baseBranch, options);
    if (pr) results.push(pr);
  }

  execSync(`git checkout ${baseBranch}`, { stdio: "pipe" });

  return results;
}

async function createGroupedPr(
  result: HealResult,
  scoredPatches: ScoredPatch[],
  baseBranch: string,
  options: PrOptions,
): Promise<PrResult | null> {
  const branchName = `contractbot/${result.apiName}/${dateSlug()}`;
  const title = `fix: update code for ${result.apiName} API changes`;
  const body = buildPrBody(result, scoredPatches);

  createBranch(branchName);

  for (const patch of result.patches) {
    applyPatchToFile(patch);
  }

  if (!hasChanges()) {
    execSync(`git checkout ${baseBranch}`, { stdio: "pipe" });
    return null;
  }

  commitChanges(`fix: migrate to updated ${result.apiName} API`, result);
  pushBranch(branchName);

  const prUrl = createPr(title, body, baseBranch, branchName, options);
  const prNumber = extractPrNumber(prUrl);

  return { url: prUrl, number: prNumber, branch: branchName, title };
}

async function createSingleFilePr(
  result: HealResult,
  patch: ScoredPatch,
  baseBranch: string,
  options: PrOptions,
): Promise<PrResult | null> {
  const safeFileName = patch.filePath
    .replace(/[/\\]/g, "-")
    .replace(/\.[^.]+$/, "");
  const branchName = `contractbot/${result.apiName}/${safeFileName}-${dateSlug()}`;
  const title = `fix(${shortPath(patch.filePath)}): update for ${result.apiName} API changes`;
  const body = buildSingleFilePrBody(result, patch);

  createBranch(branchName);
  applyPatchToFile(patch);

  if (!hasChanges()) {
    execSync(`git checkout ${baseBranch}`, { stdio: "pipe" });
    return null;
  }

  commitChanges(
    `fix(${shortPath(patch.filePath)}): migrate to updated ${result.apiName} API`,
    result,
  );
  pushBranch(branchName);

  const prUrl = createPr(title, body, baseBranch, branchName, options);
  const prNumber = extractPrNumber(prUrl);

  execSync(`git checkout ${baseBranch}`, { stdio: "pipe" });

  return { url: prUrl, number: prNumber, branch: branchName, title };
}

function buildPrBody(result: HealResult, scoredPatches: ScoredPatch[]): string {
  const avgConfidence = Math.round(
    scoredPatches.reduce((s, p) => s + p.score, 0) / scoredPatches.length,
  );

  const lines: string[] = [
    "## API Contract Migration",
    "",
    `**API:** ${result.apiName}`,
    `**Changes detected:** ${result.changes.length}`,
    `**Files updated:** ${result.patches.length}`,
    `**Average confidence:** ${avgConfidence}%`,
    "",
    "---",
    "",
    "### Breaking changes",
    "",
  ];

  const breaking = result.changes.filter((c) => c.severity === "breaking");
  if (breaking.length > 0) {
    for (const c of breaking) {
      lines.push(`- :x: ${c.description}`);
    }
  } else {
    lines.push("_None_");
  }

  const nonBreaking = result.changes.filter((c) => c.severity !== "breaking");
  if (nonBreaking.length > 0) {
    lines.push("", "### Non-breaking changes", "");
    for (const c of nonBreaking) {
      lines.push(`- :large_blue_circle: ${c.description}`);
    }
  }

  lines.push("", "---", "", "### Files modified", "");

  for (const patch of scoredPatches) {
    const badge = patch.confidence === "high"
      ? ":green_circle:"
      : patch.confidence === "medium"
        ? ":yellow_circle:"
        : ":red_circle:";
    lines.push(
      `- ${badge} \`${patch.filePath}\` — ${patch.description} (${patch.score}% confidence)`,
    );
  }

  lines.push(
    "",
    "---",
    "",
    "> :robot: This PR was auto-generated by [contractbot](https://github.com/contractbot/contractbot).",
    "> Please review the changes carefully before merging.",
  );

  return lines.join("\n");
}

function buildSingleFilePrBody(result: HealResult, patch: ScoredPatch): string {
  const lines: string[] = [
    "## API Contract Migration — Single File",
    "",
    `**API:** ${result.apiName}`,
    `**File:** \`${patch.filePath}\``,
    `**Confidence:** ${patch.score}% (${patch.confidence})`,
    "",
    "---",
    "",
    `### What changed`,
    "",
    patch.description,
    "",
    "### Why",
    "",
  ];

  const relatedChanges = result.changes.filter(
    (c) => c.field && patch.patchedContent.includes(c.field),
  );

  if (relatedChanges.length > 0) {
    for (const c of relatedChanges) {
      lines.push(`- ${c.description}`);
    }
  } else {
    for (const c of result.changes.filter((c) => c.severity === "breaking")) {
      lines.push(`- ${c.description}`);
    }
  }

  lines.push(
    "",
    "### Confidence reasoning",
    "",
  );

  for (const reason of patch.reasons) {
    lines.push(`- ${reason}`);
  }

  lines.push(
    "",
    "---",
    "",
    "> :robot: Auto-generated by [contractbot](https://github.com/contractbot/contractbot). Review before merging.",
  );

  return lines.join("\n");
}

function ensureGitClean(): void {
  const status = execSync("git status --porcelain", { encoding: "utf-8" }).trim();
  if (status) {
    throw new Error(
      "Working directory is not clean. Commit or stash changes before creating PRs.",
    );
  }
}

function ensureGhCli(): void {
  try {
    execSync("gh --version", { stdio: "pipe" });
  } catch {
    throw new Error(
      "GitHub CLI (gh) is not installed. Install it from https://cli.github.com",
    );
  }
}

function getCurrentBranch(): string {
  return execSync("git rev-parse --abbrev-ref HEAD", {
    encoding: "utf-8",
  }).trim();
}

function createBranch(name: string): void {
  execSync(`git checkout -b ${name}`, { stdio: "pipe" });
}

function applyPatchToFile(patch: FilePatch): void {
  const { writeFileSync } = require("fs");
  writeFileSync(patch.filePath, patch.patchedContent, "utf-8");
  execSync(`git add ${patch.filePath}`, { stdio: "pipe" });
}

function hasChanges(): boolean {
  const status = execSync("git status --porcelain", { encoding: "utf-8" }).trim();
  return status.length > 0;
}

function commitChanges(message: string, result: HealResult): void {
  const fullMessage = `${message}\n\nAPI changes:\n${result.changes.map((c) => `- [${c.severity}] ${c.description}`).join("\n")}\n\nGenerated by contractbot`;
  execSync(`git commit -m "${escapeShell(fullMessage)}"`, { stdio: "pipe" });
}

function pushBranch(name: string): void {
  execSync(`git push -u origin ${name}`, { stdio: "pipe" });
}

function createPr(
  title: string,
  body: string,
  baseBranch: string,
  headBranch: string,
  options: PrOptions,
): string {
  const args: string[] = [
    "gh", "pr", "create",
    "--title", `"${escapeShell(title)}"`,
    "--base", baseBranch,
    "--head", headBranch,
  ];

  if (options.draft) args.push("--draft");
  if (options.labels?.length) {
    args.push("--label", options.labels.map((l) => `"${l}"`).join(","));
  }
  if (options.reviewers?.length) {
    args.push("--reviewer", options.reviewers.join(","));
  }
  if (options.assignees?.length) {
    args.push("--assignee", options.assignees.join(","));
  }

  const bodyFile = "/tmp/contractbot-pr-body.md";
  require("fs").writeFileSync(bodyFile, body, "utf-8");
  args.push("--body-file", bodyFile);

  const output = execSync(args.join(" "), { encoding: "utf-8" }).trim();
  return output;
}

function extractPrNumber(url: string): number {
  const match = url.match(/\/pull\/(\d+)/);
  return match ? parseInt(match[1], 10) : 0;
}

function dateSlug(): string {
  return new Date().toISOString().slice(0, 10);
}

function shortPath(filePath: string): string {
  const parts = filePath.split("/");
  return parts.length > 2
    ? parts.slice(-2).join("/")
    : filePath;
}

function escapeShell(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/**
 * Displays PR creation results in the terminal.
 */
export function displayPrResults(results: PrResult[]): void {
  console.log();
  console.log(chalk.bold.green(`✓ Created ${results.length} PR(s):`));
  console.log();

  for (const pr of results) {
    console.log(`  ${chalk.cyan(`#${pr.number}`)} ${pr.title}`);
    console.log(`  ${chalk.dim(pr.url)}`);
    console.log();
  }
}
